resources:
  - name: source
    type: git
    source:
      uri: https://github.com/ripta/tpl
      branch: master
  - name: registry
    type: docker-image
    source:
      repository: ripta/tpl
      username: {{dockerhub_username}}
      password: {{dockerhub_token}}

jobs:
  - name: build
    plan:
      - get: source
        trigger: true
      - put: registry
        params:
          build: source
